//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynthNet.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SynthNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.00
        ///MVol      -0.45
        ///AVol      0.00
        ///AOsc      Saw
        ///AFine     0.00
        ///APan      0.50
        ///ASemi     0.00
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///BSemi     0.00
        ///EMAtk     0.01
        ///EMDec     0.01
        ///EMStn     1.00
        ///EMRel     0.01
        ///EFAtk     0.01
        ///EFDec     0.01
        ///EFStn     0.00
        ///EFRel     0.01
        ///FPass     LowPass
        ///FCutoff   0.10
        ///FRes      0.00
        ///FAmnt     0.01
        ///DPwr      On
        ///DTrshd    0.13
        ///LAOsc     Sine
        ///LAFrq     0.76
        ///LAMtch    False
        ///LAGain    0.66
        ///LANum     ASemi        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string _8bitMadness {
            get {
                return ResourceManager.GetString("_8bitMadness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.50
        ///AVol      0.00
        ///AOsc      Saw
        ///AFine     0.02
        ///APan      0.50
        ///ASemi     -24.00
        ///BVol      0.00
        ///BOsc      Saw
        ///BFine     0.00
        ///BPan      0.50
        ///BSemi     -12.00
        ///EMAtk     0.01
        ///EMDec     0.01
        ///EMStn     0.84
        ///EMRel     0.36
        ///FPass     LowPass
        ///FCutoff   10.77
        ///EFAtk     0.01
        ///EFDec     0.88
        ///EFStn     0.18
        ///EFRel     0.26
        ///EFAmnt    18078.29
        ///DPwr      Off
        ///DTrshd    0.10
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      4.65
        ///GMtch     False
        ///GGain     0.10
        ///GNum      --
        ///MVol      - [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Bass_Long {
            get {
                return ResourceManager.GetString("Bass_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.48
        ///AVol      0.00
        ///AOsc      Square
        ///AFine     0.00
        ///APan      0.50
        ///ASemi     -24.00
        ///BVol      0.00
        ///BOsc      Saw
        ///BFine     0.00
        ///BPan      0.50
        ///BSemi     -12.00
        ///EMAtk     0.01
        ///EMDec     0.66
        ///EMStn     0.00
        ///EMRel     0.33
        ///FPass     LowPass
        ///FCutoff   380.28
        ///EFAtk     0.01
        ///EFDec     0.25
        ///EFStn     0.00
        ///EFRel     0.17
        ///EFAmnt    9033.48
        ///DPwr      Off
        ///DTrshd    0.21
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      4.65
        ///GMtch     False
        ///GGain     0.10
        ///GNum      --
        ///MVol     [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Bass_Short {
            get {
                return ResourceManager.GetString("Bass_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.00
        ///AVol      0.00
        ///AOsc      Sine
        ///AFine     0.00
        ///APan      0.50
        ///ASemi     0.00
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///BSemi     0.00
        ///EMAtk     0.01
        ///EMDec     0.01
        ///EMStn     1.00
        ///EMRel     0.01
        ///FPass     None
        ///FCutoff   1.00
        ///EFAtk     0.01
        ///EFDec     0.01
        ///EFStn     0.00
        ///EFRel     0.01
        ///EFAmnt    1.00
        ///DPwr      Off
        ///DTrshd    0.10
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      0.01
        ///GMtch     False
        ///GGain     0.00
        ///GNum      --
        ///MVol      -11.37
        ///OPw [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Sine {
            get {
                return ResourceManager.GetString("Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.00
        ///AVol      0.00
        ///AOsc      Triangle
        ///AFine     0.00
        ///APan      0.50
        ///ASemi     12.00
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///BSemi     0.00
        ///EMAtk     0.01
        ///EMDec     0.01
        ///EMStn     1.00
        ///EMRel     0.26
        ///FPass     None
        ///FCutoff   1.00
        ///EFAtk     0.01
        ///EFDec     0.33
        ///EFStn     0.00
        ///EFRel     0.80
        ///EFAmnt    1.00
        ///DPwr      Off
        ///DTrshd    0.10
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      0.99
        ///GMtch     False
        ///GGain     0.39
        ///GNum      ASemi
        ///MVol      -11 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Siren {
            get {
                return ResourceManager.GetString("Siren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.48
        ///AVol      0.00
        ///AOsc      Saw
        ///AFine     0.00
        ///APan      0.48
        ///ASemi     0.00
        ///BVol      0.00
        ///BOsc      Triangle
        ///BFine     0.00
        ///BPan      0.55
        ///BSemi     0.00
        ///EMAtk     0.01
        ///EMDec     0.69
        ///EMStn     0.00
        ///EMRel     0.36
        ///FPass     None
        ///FCutoff   1.00
        ///EFAtk     0.01
        ///EFDec     0.01
        ///EFStn     1.00
        ///EFRel     0.17
        ///EFAmnt    1.00
        ///DPwr      Off
        ///DTrshd    0.10
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      4.65
        ///GMtch     False
        ///GGain     0.10
        ///GNum      AFine
        ///MVol      -6.38 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Synth1 {
            get {
                return ResourceManager.GetString("Synth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.00
        ///AVol      0.00
        ///AOsc      Sine
        ///AFine     0.00
        ///APan      0.50
        ///ASemi     12.00
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///BSemi     0.00
        ///EMAtk     0.01
        ///EMDec     0.01
        ///EMStn     1.00
        ///EMRel     0.26
        ///FPass     None
        ///FCutoff   1.00
        ///EFAtk     0.01
        ///EFDec     0.33
        ///EFStn     0.00
        ///EFRel     0.80
        ///EFAmnt    1.00
        ///DPwr      Off
        ///DTrshd    0.10
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      6.13
        ///GMtch     False
        ///GGain     0.91
        ///GNum      AFine
        ///MVol      -8.87
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Whistle {
            get {
                return ResourceManager.GetString("Whistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.51
        ///AVol      0.00
        ///AOsc      Saw
        ///AFine     0.00
        ///APan      0.48
        ///ASemi     -24.00
        ///BVol      0.00
        ///BOsc      Saw
        ///BFine     0.00
        ///BPan      0.56
        ///BSemi     -12.00
        ///EMAtk     0.01
        ///EMDec     0.01
        ///EMStn     1.00
        ///EMRel     0.23
        ///FPass     LowPass
        ///FCutoff   77.97
        ///EFAtk     0.01
        ///EFDec     0.01
        ///EFStn     1.00
        ///EFRel     0.17
        ///EFAmnt    1.00
        ///DPwr      Off
        ///DTrshd    0.10
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      3.57
        ///GMtch     False
        ///GGain     1.00
        ///GNum      FCutoff
        ///MVol       [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Wooble {
            get {
                return ResourceManager.GetString("Wooble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPwr      On
        ///CMix      0.40
        ///MVol      -3.10
        ///AVol      0.00
        ///AOsc      Saw
        ///AFine     -0.04
        ///APan      0.50
        ///ASemi     -12.00
        ///BVol      0.00
        ///BOsc      Saw
        ///BFine     0.02
        ///BPan      0.50
        ///BSemi     -24.00
        ///EMAtk     0.01
        ///EMDec     0.01
        ///EMStn     1.00
        ///EMRel     0.01
        ///EFAtk     0.01
        ///EFDec     0.01
        ///EFStn     0.00
        ///EFRel     0.01
        ///FPass     LowPass
        ///FCutoff   0.49
        ///FRes      0.66
        ///FAmnt     0.01
        ///DPwr      On
        ///DTrshd    0.24
        ///LAOsc     Sine
        ///LAFrq     1.27
        ///LAMtch    False
        ///LAGain    1.00
        ///LANum     FC [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string WoobleMad {
            get {
                return ResourceManager.GetString("WoobleMad", resourceCulture);
            }
        }
    }
}
